[2023-03-31 18:20:44,753] logging_util.py->logs line:78 [INFO] ----------------接口测试开始--------------------
[2023-03-31 18:20:44,754] logging_util.py->logs line:78 [INFO] 接口名称:登录成功，获得token
[2023-03-31 18:20:44,756] logging_util.py->logs line:78 [INFO] 请求方式:post
[2023-03-31 18:20:44,757] logging_util.py->logs line:78 [INFO] 请求路径:http://192.168.200.216/scrm/cms/login
[2023-03-31 18:20:44,757] logging_util.py->logs line:78 [INFO] 请求json参数:{'companyId': '1', 'password': '123456', 'username': '17740631283'}
[2023-03-31 18:20:44,757] logging_util.py->logs line:78 [INFO] 请求头:{'Content-Type': 'application/json'}
[2023-03-31 18:20:45,087] logging_util.py->logs line:78 [INFO] 预期结果:[{'equals': {'errorCode': 0}}, {'contains': 'token'}]
[2023-03-31 18:20:45,089] logging_util.py->logs line:78 [INFO] 实际结果:{'errorCode': 0, 'errorMsg': '成功', 'data': {'id': 46, 'userName': '左利娜', 'enterpriseWeChatId': 'zuoln', 'token': 'eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NDYsImlhdCI6MTY4MDI1ODA0NSwiZXhwIjoxNjgwMzAxMjQ1fQ.CNOMZVJD0ljajCm0NJMlaSpqWoozwRU58OFh7Hytw5k', 'role': {'id': 4, 'roleName': '管理员(使用线索平台和外呼功能)'}, 'domainAccount': 'zuoln'}}
[2023-03-31 18:20:45,090] logging_util.py->logs line:78 [INFO] 接口测试成功
[2023-03-31 18:20:45,090] logging_util.py->logs line:78 [INFO] ----------------接口测试结束--------------------

[2023-03-31 18:20:45,107] logging_util.py->logs line:78 [INFO] ----------------接口测试开始--------------------
[2023-03-31 18:20:45,107] logging_util.py->logs line:78 [INFO] 接口名称:检查密码为空
[2023-03-31 18:20:45,110] logging_util.py->logs line:78 [INFO] 请求方式:post
[2023-03-31 18:20:45,111] logging_util.py->logs line:78 [INFO] 请求路径:http://192.168.200.216/scrm/cms/login
[2023-03-31 18:20:45,111] logging_util.py->logs line:78 [INFO] 请求json参数:{'companyId': '1', 'password': '', 'username': '17740631283'}
[2023-03-31 18:20:45,111] logging_util.py->logs line:78 [INFO] 请求头:{'Content-Type': 'application/json'}
[2023-03-31 18:20:45,133] logging_util.py->error_log line:71 [ERROR] 断言失败errorCode不等于-2
[2023-03-31 18:20:45,133] logging_util.py->logs line:78 [INFO] 接口测试失败！！！
[2023-03-31 18:20:45,133] logging_util.py->logs line:78 [INFO] ----------------接口测试结束--------------------

[2023-03-31 18:20:45,135] logging_util.py->error_log line:71 [ERROR] 断言判断的assert_result方法异常：Traceback (most recent call last):
  File "E:\Install\python\project\scrm_api\common\request_util.py", line 110, in assert_result
    flag = self.equals_assert(value, sj_result, return_code)
  File "E:\Install\python\project\scrm_api\common\request_util.py", line 140, in equals_assert
    error_log('断言失败' + assert_key + '不等于' + str(assert_value))
  File "E:\Install\python\project\scrm_api\common\logging_util.py", line 73, in error_log
    raise Exception(message)
Exception: 断言失败errorCode不等于-2

[2023-03-31 18:20:45,135] logging_util.py->error_log line:71 [ERROR] 规范yaml的standard_yaml方法异常
[2023-03-31 18:20:45,373] logging_util.py->logs line:78 [INFO] ----------------接口测试开始--------------------
[2023-03-31 18:20:45,373] logging_util.py->logs line:78 [INFO] 接口名称:检查用户名为空
[2023-03-31 18:20:45,375] logging_util.py->logs line:78 [INFO] 请求方式:post
[2023-03-31 18:20:45,375] logging_util.py->logs line:78 [INFO] 请求路径:http://192.168.200.216/scrm/cms/login
[2023-03-31 18:20:45,375] logging_util.py->logs line:78 [INFO] 请求json参数:{'companyId': '1', 'password': '123456', 'username': ''}
[2023-03-31 18:20:45,375] logging_util.py->logs line:78 [INFO] 请求头:{'Content-Type': 'application/json'}
[2023-03-31 18:20:45,391] logging_util.py->error_log line:71 [ERROR] 断言失败errorCode不等于-2
[2023-03-31 18:20:45,392] logging_util.py->logs line:78 [INFO] 接口测试失败！！！
[2023-03-31 18:20:45,392] logging_util.py->logs line:78 [INFO] ----------------接口测试结束--------------------

[2023-03-31 18:20:45,392] logging_util.py->error_log line:71 [ERROR] 断言判断的assert_result方法异常：Traceback (most recent call last):
  File "E:\Install\python\project\scrm_api\common\request_util.py", line 110, in assert_result
    flag = self.equals_assert(value, sj_result, return_code)
  File "E:\Install\python\project\scrm_api\common\request_util.py", line 140, in equals_assert
    error_log('断言失败' + assert_key + '不等于' + str(assert_value))
  File "E:\Install\python\project\scrm_api\common\logging_util.py", line 73, in error_log
    raise Exception(message)
Exception: 断言失败errorCode不等于-2

[2023-03-31 18:20:45,392] logging_util.py->error_log line:71 [ERROR] 规范yaml的standard_yaml方法异常
[2023-03-31 18:20:45,425] logging_util.py->logs line:78 [INFO] ----------------接口测试开始--------------------
[2023-03-31 18:20:45,425] logging_util.py->logs line:78 [INFO] 接口名称:检查错误的账号
[2023-03-31 18:20:45,427] logging_util.py->logs line:78 [INFO] 请求方式:post
[2023-03-31 18:20:45,428] logging_util.py->logs line:78 [INFO] 请求路径:http://192.168.200.216/scrm/cms/login
[2023-03-31 18:20:45,428] logging_util.py->logs line:78 [INFO] 请求json参数:{'companyId': '1', 'password': '123456', 'username': '1525566456555'}
[2023-03-31 18:20:45,428] logging_util.py->logs line:78 [INFO] 请求头:{'Content-Type': 'application/json'}
[2023-03-31 18:20:45,462] logging_util.py->logs line:78 [INFO] 预期结果:[{'equals': {'errorCode': -5}}, {'contains': '未找到该账号，请确认后重新输入'}]
[2023-03-31 18:20:45,462] logging_util.py->logs line:78 [INFO] 实际结果:{'errorCode': -5, 'errorMsg': '未找到该账号，请确认后重新输入', 'data': None}
[2023-03-31 18:20:45,462] logging_util.py->logs line:78 [INFO] 接口测试成功
[2023-03-31 18:20:45,462] logging_util.py->logs line:78 [INFO] ----------------接口测试结束--------------------

[2023-03-31 18:20:45,466] logging_util.py->logs line:78 [INFO] ----------------接口测试开始--------------------
[2023-03-31 18:20:45,466] logging_util.py->logs line:78 [INFO] 接口名称:检查错误的密码
[2023-03-31 18:20:45,468] logging_util.py->logs line:78 [INFO] 请求方式:post
[2023-03-31 18:20:45,468] logging_util.py->logs line:78 [INFO] 请求路径:http://192.168.200.216/scrm/cms/login
[2023-03-31 18:20:45,468] logging_util.py->logs line:78 [INFO] 请求json参数:{'companyId': '1', 'password': '1232456', 'username': '17740631283'}
[2023-03-31 18:20:45,468] logging_util.py->logs line:78 [INFO] 请求头:{'Content-Type': 'application/json'}
[2023-03-31 18:20:45,652] logging_util.py->logs line:78 [INFO] 预期结果:[{'equals': {'errorCode': -3}}, {'contains': '账号或密码或公司错误'}]
[2023-03-31 18:20:45,653] logging_util.py->logs line:78 [INFO] 实际结果:{'errorCode': -3, 'errorMsg': '账号或密码或公司错误', 'data': None}
[2023-03-31 18:20:45,654] logging_util.py->logs line:78 [INFO] 接口测试成功
[2023-03-31 18:20:45,655] logging_util.py->logs line:78 [INFO] ----------------接口测试结束--------------------

