[2023-04-03 18:25:33,676] logging_util.py->logs line:78 [INFO] ----------------接口测试开始--------------------
[2023-04-03 18:25:33,676] logging_util.py->logs line:78 [INFO] 接口名称:登录成功，获得token
[2023-04-03 18:25:33,679] logging_util.py->logs line:78 [INFO] 请求方式:post
[2023-04-03 18:25:33,679] logging_util.py->logs line:78 [INFO] 请求路径:http://192.168.200.216/scrm/cms/login
[2023-04-03 18:25:33,679] logging_util.py->logs line:78 [INFO] 请求json参数:{'companyId': '1', 'password': '123456', 'username': '17740631283'}
[2023-04-03 18:25:33,679] logging_util.py->logs line:78 [INFO] 请求头:{'Content-Type': 'application/json'}
[2023-04-03 18:25:33,891] logging_util.py->logs line:78 [INFO] 预期结果:[{'equals': {'errorCode': 0}}, {'contains': 'token'}]
[2023-04-03 18:25:33,893] logging_util.py->logs line:78 [INFO] 实际结果:{'errorCode': 0, 'errorMsg': '成功', 'data': {'id': 46, 'userName': '左利娜', 'enterpriseWeChatId': 'zuoln', 'token': 'eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NDYsImlhdCI6MTY4MDUxNzUzMywiZXhwIjoxNjgwNTYwNzMzfQ.cVsa0LRHjQMum8o4zf3kJXnTaSHumRmdrrNpDUt0MWE', 'role': {'id': 4, 'roleName': '管理员(使用线索平台和外呼功能)'}, 'domainAccount': 'zuoln'}}
[2023-04-03 18:25:33,893] logging_util.py->logs line:78 [INFO] 接口测试成功
[2023-04-03 18:25:33,893] logging_util.py->logs line:78 [INFO] ----------------接口测试结束--------------------

[2023-04-03 18:25:33,899] logging_util.py->logs line:78 [INFO] ----------------接口测试开始--------------------
[2023-04-03 18:25:33,899] logging_util.py->logs line:78 [INFO] 接口名称:检查密码为空
[2023-04-03 18:25:33,901] logging_util.py->logs line:78 [INFO] 请求方式:post
[2023-04-03 18:25:33,901] logging_util.py->logs line:78 [INFO] 请求路径:http://192.168.200.216/scrm/cms/login
[2023-04-03 18:25:33,901] logging_util.py->logs line:78 [INFO] 请求json参数:{'companyId': '1', 'password': '', 'username': '17740631283'}
[2023-04-03 18:25:33,901] logging_util.py->logs line:78 [INFO] 请求头:{'Content-Type': 'application/json'}
[2023-04-03 18:25:33,917] logging_util.py->error_log line:71 [ERROR] 断言失败，返回的结果中不包含账号或密码为空
[2023-04-03 18:25:33,917] logging_util.py->logs line:78 [INFO] 接口测试失败！！！
[2023-04-03 18:25:33,917] logging_util.py->logs line:78 [INFO] ----------------接口测试结束--------------------

[2023-04-03 18:25:33,918] logging_util.py->error_log line:71 [ERROR] 断言判断的assert_result方法异常：Traceback (most recent call last):
  File "E:\Install\python\project\scrm_api\common\request_util.py", line 113, in assert_result
    flag = self.contains_assert(value, sj_result)
  File "E:\Install\python\project\scrm_api\common\request_util.py", line 152, in contains_assert
    error_log('断言失败，返回的结果中不包含' + str(value))
  File "E:\Install\python\project\scrm_api\common\logging_util.py", line 73, in error_log
    raise Exception(message)
Exception: 断言失败，返回的结果中不包含账号或密码为空

[2023-04-03 18:25:33,918] logging_util.py->error_log line:71 [ERROR] 规范yaml的standard_yaml方法异常
[2023-04-03 18:25:34,138] logging_util.py->logs line:78 [INFO] ----------------接口测试开始--------------------
[2023-04-03 18:25:34,138] logging_util.py->logs line:78 [INFO] 接口名称:检查用户名为空
[2023-04-03 18:25:34,141] logging_util.py->logs line:78 [INFO] 请求方式:post
[2023-04-03 18:25:34,141] logging_util.py->logs line:78 [INFO] 请求路径:http://192.168.200.216/scrm/cms/login
[2023-04-03 18:25:34,141] logging_util.py->logs line:78 [INFO] 请求json参数:{'companyId': '1', 'password': '123456', 'username': ''}
[2023-04-03 18:25:34,141] logging_util.py->logs line:78 [INFO] 请求头:{'Content-Type': 'application/json'}
[2023-04-03 18:25:34,159] logging_util.py->error_log line:71 [ERROR] 断言失败，返回的结果中不包含账号或密码为空
[2023-04-03 18:25:34,159] logging_util.py->logs line:78 [INFO] 接口测试失败！！！
[2023-04-03 18:25:34,159] logging_util.py->logs line:78 [INFO] ----------------接口测试结束--------------------

[2023-04-03 18:25:34,160] logging_util.py->error_log line:71 [ERROR] 断言判断的assert_result方法异常：Traceback (most recent call last):
  File "E:\Install\python\project\scrm_api\common\request_util.py", line 113, in assert_result
    flag = self.contains_assert(value, sj_result)
  File "E:\Install\python\project\scrm_api\common\request_util.py", line 152, in contains_assert
    error_log('断言失败，返回的结果中不包含' + str(value))
  File "E:\Install\python\project\scrm_api\common\logging_util.py", line 73, in error_log
    raise Exception(message)
Exception: 断言失败，返回的结果中不包含账号或密码为空

[2023-04-03 18:25:34,160] logging_util.py->error_log line:71 [ERROR] 规范yaml的standard_yaml方法异常
[2023-04-03 18:25:34,199] logging_util.py->logs line:78 [INFO] ----------------接口测试开始--------------------
[2023-04-03 18:25:34,200] logging_util.py->logs line:78 [INFO] 接口名称:检查错误的账号
[2023-04-03 18:25:34,201] logging_util.py->logs line:78 [INFO] 请求方式:post
[2023-04-03 18:25:34,201] logging_util.py->logs line:78 [INFO] 请求路径:http://192.168.200.216/scrm/cms/login
[2023-04-03 18:25:34,202] logging_util.py->logs line:78 [INFO] 请求json参数:{'companyId': '1', 'password': '123456', 'username': '1525566456555'}
[2023-04-03 18:25:34,202] logging_util.py->logs line:78 [INFO] 请求头:{'Content-Type': 'application/json'}
[2023-04-03 18:25:34,228] logging_util.py->logs line:78 [INFO] 预期结果:[{'equals': {'errorCode': -5}}, {'contains': '未找到该账号，请确认后重新输入'}]
[2023-04-03 18:25:34,228] logging_util.py->logs line:78 [INFO] 实际结果:{'errorCode': -5, 'errorMsg': '未找到该账号，请确认后重新输入', 'data': None}
[2023-04-03 18:25:34,228] logging_util.py->logs line:78 [INFO] 接口测试成功
[2023-04-03 18:25:34,228] logging_util.py->logs line:78 [INFO] ----------------接口测试结束--------------------

[2023-04-03 18:25:34,234] logging_util.py->logs line:78 [INFO] ----------------接口测试开始--------------------
[2023-04-03 18:25:34,234] logging_util.py->logs line:78 [INFO] 接口名称:检查错误的密码
[2023-04-03 18:25:34,236] logging_util.py->logs line:78 [INFO] 请求方式:post
[2023-04-03 18:25:34,236] logging_util.py->logs line:78 [INFO] 请求路径:http://192.168.200.216/scrm/cms/login
[2023-04-03 18:25:34,236] logging_util.py->logs line:78 [INFO] 请求json参数:{'companyId': '1', 'password': '1232456', 'username': '17740631283'}
[2023-04-03 18:25:34,236] logging_util.py->logs line:78 [INFO] 请求头:{'Content-Type': 'application/json'}
[2023-04-03 18:25:34,372] logging_util.py->logs line:78 [INFO] 预期结果:[{'equals': {'errorCode': -3}}, {'contains': '账号或密码或公司错误'}]
[2023-04-03 18:25:34,372] logging_util.py->logs line:78 [INFO] 实际结果:{'errorCode': -3, 'errorMsg': '账号或密码或公司错误', 'data': None}
[2023-04-03 18:25:34,372] logging_util.py->logs line:78 [INFO] 接口测试成功
[2023-04-03 18:25:34,373] logging_util.py->logs line:78 [INFO] ----------------接口测试结束--------------------

